export type AvitoPricing = "free" | "freemium" | "paid";

export type AvitoTool = {
  slug: string;
  name: string;
  types: string[];
  categories: string[];
  description: string;
  price: string;
  /** нормализованный тариф для фильтра */
  pricing: AvitoPricing;
  website: string;
  status: "active" | "changed" | "dead";
  lastChecked: string;
  /** official = работает через официальный Avito API; unofficial = сторонний доступ; none = не относится */
  api: "official" | "unofficial" | "none";
  /** серая зона правил Авито (парсинг, автодействия, мультиаккаунт) */
  risk: boolean;
  /** премиальная витрина наверху каталога */
  featured?: boolean;
  /** короткий слоган для featured-блока */
  highlight?: string;
  /** дополнительные ссылки внутри одной карточки (набор инструментов) */
  links?: { label: string; url: string }[];
};

export type AvitoCategory = {
  slug: string;
  name: string;
  icon: string;
  description: string;
};

/** Сценарий «мне нужно решить задачу» — подбирает набор категорий */
export type AvitoJob = {
  slug: string;
  title: string;
  hint: string;
  categories: string[];
};

export const avitoCategories: AvitoCategory[] = [
  { slug: "analytics", name: "Аналитика", icon: "🔎", description: "Спрос, ниши, ключевые слова, своя статистика" },
  { slug: "parsing", name: "Парсеры", icon: "🕷", description: "Сбор объявлений, цен, продавцов по фильтрам Авито" },
  { slug: "autoposting", name: "Автопостинг", icon: "📤", description: "Массовая загрузка, републикация, уникализация" },
  { slug: "chats", name: "Чаты и автоответы", icon: "💬", description: "Переписка, уведомления, сценарии ответов" },
  { slug: "ai", name: "AI для Авито", icon: "🤖", description: "Тексты, квалификация лидов, AI-переписка" },
  { slug: "extensions", name: "Расширения", icon: "🧩", description: "Chrome / Яндекс Браузер прямо на Авито" },
  { slug: "competitors", name: "Анализ конкурентов", icon: "📊", description: "Выдача, продавцы, цены, мониторинг ниши" },
  { slug: "promotion", name: "Продвижение", icon: "🎯", description: "Ставки, реклама, бидеры, эффективность" },
  { slug: "crm", name: "CRM и интеграции", icon: "🔗", description: "Лиды, сделки, связки, API, 1С" },
  { slug: "design", name: "Объявления и фото", icon: "🖼", description: "Карточки, инфографика, уникализация фото" },
];

export const avitoJobs: AvitoJob[] = [
  {
    slug: "find-clients",
    title: "Найти клиентов",
    hint: "Парсеры + конкуренты + аналитика",
    categories: ["parsing", "competitors", "analytics"],
  },
  {
    slug: "mass-post",
    title: "Разместить много объявлений",
    hint: "Автозагрузка + уникализация + аккаунты",
    categories: ["autoposting", "design", "extensions"],
  },
  {
    slug: "answer-faster",
    title: "Отвечать быстрее",
    hint: "AI-чаты + автоответы + CRM",
    categories: ["chats", "ai", "crm"],
  },
  {
    slug: "understand-niche",
    title: "Понять нишу",
    hint: "Спрос + конкуренты + цены",
    categories: ["analytics", "competitors", "promotion"],
  },
];

export const avitoPricingFilters: { slug: AvitoPricing | "all"; label: string }[] = [
  { slug: "all", label: "Любая цена" },
  { slug: "free", label: "Бесплатно" },
  { slug: "freemium", label: "Есть бесплатный тариф" },
  { slug: "paid", label: "Платный" },
];

export const avitoTools: AvitoTool[] = [
  // ── Нативный инструмент ProektMap ──────────────────────────
  {
    slug: "avito-photo-lab",
    name: "Avito Photo Lab (ProektMap)",
    types: ["Онлайн-утилита", "Инструмент"],
    categories: ["design", "autoposting"],
    description:
      "Инженерный конвейер уникализации товарных фото для Авито: контроль визуального сходства (pHash/dHash), сборщик непересекающихся наборов под 20+ объявлений, сканер дубликатов и Product Lock AI.",
    price: "Бесплатно",
    pricing: "free",
    website: "https://proektmap.ru/services/avito-photo-uniquizer",
    status: "active",
    lastChecked: "2026-08-30",
    api: "none",
    risk: false,
    featured: true,
    highlight: "Нативный инструмент ProektMap: пакетная уникализация, контроль схожести и сборка наборов",
    links: [
      { label: "Открыть Avito Photo Lab", url: "/services/avito-photo-uniquizer" },
      { label: "Готовое решение: Запустить AI-магазин на Авито", url: "/resheniya/avito-business" },
      { label: "Каталог микросервисов", url: "/services" },
    ],
  },

  // ── Премиум-партнёр ───────────────────────────────────────
  {
    slug: "bananlab",
    name: "BananLab",
    types: ["SaaS", "Расширение"],
    categories: ["autoposting", "analytics", "competitors", "design", "extensions"],
    description:
      "Автозагрузка и републикация, уникализация фото и текста, статистика по клиентам и конкурентам, чат Авито в Telegram. Есть браузерная аналитика выдачи. Для авитологов и компаний.",
    price: "от 500 ₽ / аккаунт · 14 дней бесплатно",
    pricing: "freemium",
    website: "https://bananlab.ru/?fr=764",
    status: "active",
    lastChecked: "2026-08-21",
    api: "unofficial",
    risk: true,
    featured: true,
    highlight: "Профессиональная автозагрузка для авитологов — премиум в каталоге ProektMap",
    links: [
      { label: "Сайт BananLab", url: "https://bananlab.ru/?fr=764" },
      { label: "Расширение: аналитика Авито (Chrome)", url: "https://chromewebstore.google.com/search/BananLab" },
    ],
  },

  // ── Из подборки Алексея (21.08) ───────────────────────────
  {
    slug: "likestats",
    name: "LikeStats",
    types: ["SaaS"],
    categories: ["analytics", "competitors"],
    description:
      "Анализ продавцов, категорий, спроса, конкурентов и своих объявлений на Авито — кабинет аналитики.",
    price: "Freemium",
    pricing: "freemium",
    website: "https://likestats.io/",
    status: "active",
    lastChecked: "2026-08-21",
    api: "none",
    risk: false,
  },
  {
    slug: "likestats-extension",
    name: "LikeStats Extension",
    types: ["Расширение"],
    categories: ["extensions", "analytics", "competitors"],
    description: "Статистика LikeStats прямо внутри страниц Авито — выдача, продавцы, спрос.",
    price: "Freemium",
    pricing: "freemium",
    website: "https://chromewebstore.google.com/detail/efjdhfpogpilmdljhiinfmfhoppeklel",
    status: "active",
    lastChecked: "2026-08-21",
    api: "none",
    risk: false,
  },
  {
    slug: "avitomatika",
    name: "Авитоматика",
    types: ["SaaS"],
    categories: ["autoposting", "chats", "analytics"],
    description:
      "Автозагрузка и массовая публикация, мессенджер по чатам Авито, уведомления и аналитика в одном сервисе.",
    price: "по тарифам сервиса",
    pricing: "paid",
    website: "https://avitomatika.ru/",
    status: "active",
    lastChecked: "2026-08-21",
    api: "unofficial",
    risk: true,
  },
  {
    slug: "avibox-hub",
    name: "AviBOX HUB",
    types: ["SaaS"],
    categories: ["crm", "chats", "analytics", "ai", "autoposting"],
    description:
      "Управление аккаунтами, объявлениями, чатами и аналитикой. Центр сообщений, AI-ответы на отзывы, уведомления в Telegram.",
    price: "центр сообщений бесплатно · доп. функции посуточно",
    pricing: "freemium",
    website: "https://avibox.ru/",
    status: "active",
    lastChecked: "2026-08-21",
    api: "official",
    risk: false,
    links: [
      { label: "AviBOX HUB", url: "https://avibox.ru/" },
      { label: "Кабинет hub.avibox.ru", url: "https://hub.avibox.ru/" },
    ],
  },
  {
    slug: "aviflow",
    name: "Авифлоу",
    types: ["SaaS", "AI"],
    categories: ["ai", "chats"],
    description:
      "AI-ответы в чатах Авито, квалификация лидов и автоматизация переписки — заточен под сценарии площадки.",
    price: "по тарифам сервиса",
    pricing: "paid",
    website: "https://avitoflow.org/",
    status: "active",
    lastChecked: "2026-08-21",
    api: "unofficial",
    risk: true,
  },
  {
    slug: "parser24",
    name: "Parser24",
    types: ["SaaS", "API"],
    categories: ["parsing", "competitors"],
    description:
      "Сбор карточек по готовой ссылке с фильтрами Авито: продавец, заголовок, цена, город, категория, просмотры, фото, координаты и др. — структурированные данные для лаборатории.",
    price: "по тарифам сервиса",
    pricing: "paid",
    website: "https://parser24.ru/",
    status: "active",
    lastChecked: "2026-08-21",
    api: "none",
    risk: true,
  },
  {
    slug: "ave-blacklist",
    name: "Ave Blacklist",
    types: ["Расширение"],
    categories: ["extensions"],
    description: "Блокировка объявлений и продавцов (спам, агентства) прямо в выдаче Авито.",
    price: "Бесплатно",
    pricing: "free",
    website: "https://chromewebstore.google.com/detail/ave-blacklist/jhobdoodiicgomhcmcdapbdehndbhkfj",
    status: "active",
    lastChecked: "2026-08-21",
    api: "none",
    risk: false,
  },
  {
    slug: "autoanswersbot",
    name: "AutoAnswersBot",
    types: ["SaaS", "Расширение"],
    categories: ["chats", "ai", "extensions", "crm"],
    description:
      "Автоматизация ответов и работа с чатами Авито: фильтры, сценарии, уведомления в Telegram. Есть Chrome-расширение для быстрого подключения.",
    price: "по тарифам · есть базовый план",
    pricing: "paid",
    website: "https://autoanswers.ru/",
    status: "active",
    lastChecked: "2026-08-21",
    api: "official",
    risk: false,
    links: [
      { label: "Сайт AutoAnswersBot", url: "https://autoanswers.ru/" },
      { label: "Chrome-расширение AutoAnswers Avito", url: "https://chromewebstore.google.com/detail/autoanswers-avito/idcjmpcajmfinhlndjblehmbobifflgn" },
    ],
  },

  // ── Аналитика ──────────────────────────────────────────────
  {
    slug: "yandex-wordstat",
    name: "Яндекс Вордстат",
    types: ["Web"],
    categories: ["analytics"],
    description: "Спрос и ключевые запросы по нишам Авито — с чего начинать поиск ниши.",
    price: "Бесплатно",
    pricing: "free",
    website: "https://wordstat.yandex.ru",
    status: "active",
    lastChecked: "2026-08-18",
    api: "none",
    risk: false,
  },
  {
    slug: "google-trends",
    name: "Google Trends",
    types: ["Web"],
    categories: ["analytics"],
    description: "Тренды спроса и сезонность по категориям товаров.",
    price: "Бесплатно",
    pricing: "free",
    website: "https://trends.google.ru",
    status: "active",
    lastChecked: "2026-08-18",
    api: "none",
    risk: false,
  },
  {
    slug: "keys-so",
    name: "Keys.so",
    types: ["SaaS"],
    categories: ["analytics"],
    description: "Семантика и подбор ключевых слов для карточек объявлений.",
    price: "от 590 ₽/мес",
    pricing: "paid",
    website: "https://keys.so",
    status: "active",
    lastChecked: "2026-08-18",
    api: "none",
    risk: false,
  },
  {
    slug: "mpstats",
    name: "MPStats",
    types: ["SaaS"],
    categories: ["analytics", "competitors"],
    description: "Аналитика продавцов, товаров и ниш маркетплейсов.",
    price: "Freemium",
    pricing: "freemium",
    website: "https://mpstats.io",
    status: "active",
    lastChecked: "2026-08-18",
    api: "none",
    risk: false,
  },

  // ── Парсинг (серая зона) ──────────────────────────────────
  {
    slug: "apify",
    name: "Apify",
    types: ["SaaS", "API"],
    categories: ["parsing", "crm"],
    description: "Готовые парсеры и автоматизация сбора данных с площадок.",
    price: "Freemium",
    pricing: "freemium",
    website: "https://apify.com",
    status: "active",
    lastChecked: "2026-08-18",
    api: "none",
    risk: true,
  },
  {
    slug: "octoparse",
    name: "Octoparse",
    types: ["Desktop", "SaaS"],
    categories: ["parsing"],
    description: "Визуальный парсер сайтов без кода.",
    price: "Freemium",
    pricing: "freemium",
    website: "https://octoparse.com",
    status: "active",
    lastChecked: "2026-08-18",
    api: "none",
    risk: true,
  },

  // ── Автопостинг ───────────────────────────────────────────
  {
    slug: "avito-business-api",
    name: "Avito Business API",
    types: ["API"],
    categories: ["autoposting", "crm", "chats"],
    description: "Официальный API Авито: объявления, сообщения, статистика, продвижение.",
    price: "по тарифам Авито",
    pricing: "paid",
    website: "https://developers.avito.ru",
    status: "active",
    lastChecked: "2026-08-18",
    api: "official",
    risk: false,
  },
  {
    slug: "avitool",
    name: "AviTool",
    types: ["Desktop", "Windows"],
    categories: ["autoposting", "analytics", "design"],
    description:
      "Десктопная программа для Windows: массово размещает, редактирует, продлевает, поднимает и удаляет объявления; клонирует по городам и аккаунтам; шаблоны, уникализация текста и фото, расписание, Excel/XML, прокси и статистика.",
    price: "разовая лицензия ≈ от 8 900 ₽ · без абонентки · без пробного периода",
    pricing: "paid",
    website: "https://codestudio.net/ru/products/avitool/",
    status: "active",
    lastChecked: "2026-08-21",
    api: "unofficial",
    risk: true,
  },
  {
    slug: "av-poster",
    name: "Av-Poster (XML Avito)",
    types: ["Desktop"],
    categories: ["autoposting", "crm"],
    description:
      "Помощник для официальной «Автозагрузки» Авито: конвертирует таблицы в XML и готовит архивы с изображениями. Сам не публикует — работает со штатной Автозагрузкой.",
    price: "разовая лицензия ≈ 500 ₽",
    pricing: "paid",
    website: "https://av-poster.ru/",
    status: "active",
    lastChecked: "2026-08-21",
    api: "none",
    risk: false,
  },
  {
    slug: "avito-autoload",
    name: "Автозагрузка Авито",
    types: ["Web"],
    categories: ["autoposting", "crm"],
    description:
      "Официальный инструмент площадки: публикация и обновление объявлений по расписанию из XML, CSV или Excel.",
    price: "нужен тариф «Расширенный» или «Максимальный»",
    pricing: "paid",
    website: "https://www.avito.ru/business/autoload",
    status: "active",
    lastChecked: "2026-08-21",
    api: "official",
    risk: false,
  },

  // ── AI ────────────────────────────────────────────────────
  {
    slug: "gigachat",
    name: "GigaChat",
    types: ["AI"],
    categories: ["ai"],
    description: "Русскоязычные тексты: заголовки, описания, ответы клиентам.",
    price: "Freemium",
    pricing: "freemium",
    website: "https://giga.chat",
    status: "active",
    lastChecked: "2026-08-18",
    api: "none",
    risk: false,
  },
  {
    slug: "yandexgpt",
    name: "YandexGPT",
    types: ["AI"],
    categories: ["ai"],
    description: "Генерация текстов от Яндекса — описания и заголовки объявлений.",
    price: "Freemium",
    pricing: "freemium",
    website: "https://aistudio.yandex.ru",
    status: "active",
    lastChecked: "2026-08-18",
    api: "none",
    risk: false,
  },
  {
    slug: "shedevrum",
    name: "Шедеврум",
    types: ["AI", "Mobile"],
    categories: ["ai", "design"],
    description: "Генерация изображений для карточек товаров.",
    price: "Бесплатно",
    pricing: "free",
    website: "https://shedevrum.ai",
    status: "active",
    lastChecked: "2026-08-18",
    api: "none",
    risk: false,
  },
  {
    slug: "chatgpt",
    name: "ChatGPT",
    types: ["AI"],
    categories: ["ai"],
    description: "Заголовки, описания и сценарии ответов клиентам.",
    price: "Freemium",
    pricing: "freemium",
    website: "https://chatgpt.com",
    status: "active",
    lastChecked: "2026-08-18",
    api: "none",
    risk: false,
  },

  // ── Расширения ────────────────────────────────────────────
  {
    slug: "avtoolspro",
    name: "AvToolsPro",
    types: ["Расширение"],
    categories: ["extensions", "analytics", "competitors"],
    description: "Аналитика объявлений, продавцов и поисковых запросов прямо в браузере на Авито.",
    price: "Freemium",
    pricing: "freemium",
    website: "https://chromewebstore.google.com/detail/cnppacflkmijmiknhacgdllcakjpdhga",
    status: "active",
    lastChecked: "2026-08-21",
    api: "none",
    risk: false,
  },
  {
    slug: "avito-filter",
    name: "Avito Filter",
    types: ["Расширение"],
    categories: ["extensions"],
    description: "Скрывает уже просмотренные и ненужные объявления в выдаче Авито (и OLX).",
    price: "Бесплатно",
    pricing: "free",
    website: "https://chromewebstore.google.com/detail/nahkjkioimodegoeoklgclokbjocbpgk",
    status: "active",
    lastChecked: "2026-08-21",
    api: "none",
    risk: false,
  },
  {
    slug: "avito-comment-adder",
    name: "Avito Comment Adder",
    types: ["Расширение"],
    categories: ["extensions", "competitors"],
    description: "Личные заметки к объявлениям на Авито с экспортом/импортом базы комментариев.",
    price: "Бесплатно",
    pricing: "free",
    website: "https://chromewebstore.google.com/detail/hpoolpnhodapahmeifnlmookojkiaoai",
    status: "active",
    lastChecked: "2026-08-21",
    api: "none",
    risk: false,
  },
  {
    slug: "multiaccount-avito",
    name: "Multiaccount",
    types: ["Расширение"],
    categories: ["extensions", "autoposting"],
    description: "Профили и отдельные cookies для нескольких аккаунтов Авито в одном браузере.",
    price: "Бесплатно / Freemium",
    pricing: "freemium",
    website: "https://chromewebstore.google.com/detail/bjhogabbcklgmknmpkcibognokhlebkn",
    status: "active",
    lastChecked: "2026-08-21",
    api: "none",
    risk: true,
  },
  {
    slug: "avitolog-bez-prikras-kit",
    name: "Набор «Авитолог без прикрас»",
    types: ["Telegram", "Расширение", "Скрипт"],
    categories: ["chats", "extensions", "promotion", "competitors", "ai"],
    description:
      "Четыре рабочих инструмента из канала: Telegram-бот ответов; браузерное приложение (выдача, конкуренты); бесплатный бидер; скрипт переименования файлов на Яндекс Диске.",
    price: "Бесплатно · ИИ-продавец отдельно платно",
    pricing: "freemium",
    website: "https://t.me/avitolog_bez_prikras",
    status: "active",
    lastChecked: "2026-08-21",
    api: "unofficial",
    risk: true,
    links: [
      { label: "1. Telegram-бот ответов + автоответы по времени", url: "https://t.me/avitolog_bez_prikras/710" },
      { label: "Результаты ИИ-продавца (платно)", url: "https://t.me/avitologi_help/18689" },
      { label: "2. Расширение: выдача, конкуренты, «Могу сегодня», ×2", url: "https://t.me/avitolog_bez_prikras/686" },
      { label: "3. Бесплатный бидер (до 3 объявлений)", url: "https://t.me/avitolog_bez_prikras/831" },
      { label: "4. Переименование файлов на Яндекс Диске", url: "https://t.me/avitolog_bez_prikras/360" },
    ],
  },

  // ── CRM и чаты ────────────────────────────────────────────
  {
    slug: "botman",
    name: "BotMan",
    types: ["SaaS"],
    categories: ["chats", "ai", "crm"],
    description: "Автоответы и сценарии диалогов в чатах Авито через официальный API; заявки в одном окне.",
    price: "Freemium · нужен тариф Авито Pro",
    pricing: "freemium",
    website: "https://botman.pro/",
    status: "active",
    lastChecked: "2026-08-21",
    api: "official",
    risk: false,
  },
  {
    slug: "pachca",
    name: "Пачка",
    types: ["SaaS"],
    categories: ["chats", "crm"],
    description: "Переписки с клиентами из разных каналов, включая Авито, в одном рабочем пространстве.",
    price: "от 199 ₽/мес",
    pricing: "paid",
    website: "https://pachca.com/",
    status: "active",
    lastChecked: "2026-08-21",
    api: "none",
    risk: false,
  },
  {
    slug: "amocrm",
    name: "amoCRM",
    types: ["SaaS"],
    categories: ["crm"],
    description: "Лиды и сделки, интеграция с чатами Авито.",
    price: "от 499 ₽/мес",
    pricing: "paid",
    website: "https://amocrm.ru",
    status: "active",
    lastChecked: "2026-08-18",
    api: "none",
    risk: false,
  },
  {
    slug: "bitrix24",
    name: "Bitrix24",
    types: ["SaaS"],
    categories: ["crm", "chats"],
    description: "CRM, чаты и автоматизация в одном окне, в том числе с Авито.",
    price: "Freemium",
    pricing: "freemium",
    website: "https://bitrix24.ru",
    status: "active",
    lastChecked: "2026-08-18",
    api: "none",
    risk: false,
  },
  {
    slug: "retailcrm",
    name: "RetailCRM",
    types: ["SaaS"],
    categories: ["crm"],
    description: "Управление заказами и клиентами из Авито.",
    price: "от 990 ₽/мес",
    pricing: "paid",
    website: "https://retailcrm.ru",
    status: "active",
    lastChecked: "2026-08-18",
    api: "none",
    risk: false,
  },
  {
    slug: "jivo",
    name: "Jivo",
    types: ["SaaS"],
    categories: ["chats", "crm"],
    description: "Единый мессенджер для операторов: Авито, сайт, соцсети и статистика команды.",
    price: "Freemium",
    pricing: "freemium",
    website: "https://www.jivo.ru/",
    status: "active",
    lastChecked: "2026-08-21",
    api: "none",
    risk: false,
  },
  {
    slug: "envybox",
    name: "EnvyBox",
    types: ["SaaS"],
    categories: ["chats", "crm"],
    description: "CRM-мессенджер и виджеты: ответы на сообщения Авито и заявки с сайта.",
    price: "от 720 ₽/мес",
    pricing: "paid",
    website: "https://envybox.io/",
    status: "active",
    lastChecked: "2026-08-21",
    api: "none",
    risk: false,
  },

  // ── Аналитика звонков и ROI ───────────────────────────────
  {
    slug: "avito-calltracking",
    name: "Коллтрекинг Авито",
    types: ["Web"],
    categories: ["analytics", "promotion"],
    description: "Официальная запись и аналитика звонков по объявлениям в кабинете Авито.",
    price: "в платных тарифах Авито",
    pricing: "paid",
    website: "https://www.avito.ru/business/tools",
    status: "active",
    lastChecked: "2026-08-21",
    api: "official",
    risk: false,
  },
  {
    slug: "calltouch",
    name: "Calltouch",
    types: ["SaaS"],
    categories: ["analytics", "crm"],
    description: "Сквозная аналитика и коллтрекинг: откуда пришёл звонок и какая отдача каналов, включая Авито.",
    price: "от 990 ₽/мес",
    pricing: "paid",
    website: "https://www.calltouch.ru/",
    status: "active",
    lastChecked: "2026-08-21",
    api: "none",
    risk: false,
  },
  {
    slug: "roistat",
    name: "Roistat",
    types: ["SaaS"],
    categories: ["analytics", "crm", "promotion"],
    description: "Сквозная аналитика рекламы: расходы → лиды → сделки → прибыль, есть интеграция с Авито.",
    price: "по тарифам",
    pricing: "paid",
    website: "https://roistat.com/",
    status: "active",
    lastChecked: "2026-08-21",
    api: "none",
    risk: false,
  },

  // ── Дизайн ────────────────────────────────────────────────
  {
    slug: "photoroom",
    name: "Photoroom",
    types: ["SaaS", "Mobile"],
    categories: ["design"],
    description: "Удаление фона и карточки товаров с AI.",
    price: "Freemium",
    pricing: "freemium",
    website: "https://photoroom.com",
    status: "active",
    lastChecked: "2026-08-18",
    api: "none",
    risk: false,
  },
  {
    slug: "canva",
    name: "Canva",
    types: ["SaaS"],
    categories: ["design"],
    description: "Дизайн карточек и инфографика по шаблонам.",
    price: "Freemium",
    pricing: "freemium",
    website: "https://canva.com",
    status: "active",
    lastChecked: "2026-08-18",
    api: "none",
    risk: false,
  },
  {
    slug: "remove-bg",
    name: "remove.bg",
    types: ["SaaS"],
    categories: ["design"],
    description: "Удаление фона с фото в один клик.",
    price: "Freemium",
    pricing: "freemium",
    website: "https://remove.bg",
    status: "active",
    lastChecked: "2026-08-18",
    api: "none",
    risk: false,
  },

  // ── Продвижение ───────────────────────────────────────────
  {
    slug: "avito-promotion",
    name: "Авито Продвижение",
    types: ["Web"],
    categories: ["promotion"],
    description: "Встроенные инструменты продвижения объявлений Авито.",
    price: "по тарифам Авито",
    pricing: "paid",
    website: "https://avito.ru/pro",
    status: "active",
    lastChecked: "2026-08-18",
    api: "official",
    risk: false,
  },

  // ── Интеграции ────────────────────────────────────────────
  {
    slug: "albato",
    name: "Albato",
    types: ["SaaS"],
    categories: ["crm"],
    description: "Связка сервисов и автоматизация без кода.",
    price: "Freemium",
    pricing: "freemium",
    website: "https://albato.ru",
    status: "active",
    lastChecked: "2026-08-18",
    api: "none",
    risk: false,
  },
  {
    slug: "n8n",
    name: "n8n",
    types: ["Open Source", "SaaS"],
    categories: ["crm", "parsing"],
    description: "Автоматизация рабочих процессов с гибкими сценариями.",
    price: "Freemium",
    pricing: "freemium",
    website: "https://n8n.io",
    status: "active",
    lastChecked: "2026-08-18",
    api: "none",
    risk: false,
  },

  // ── Комплекс ──────────────────────────────────────────────
  {
    slug: "avitolog",
    name: "Авитолог",
    types: ["SaaS", "AI"],
    categories: ["autoposting", "chats", "ai"],
    description: "Автоматизация работы с Авито: объявления, ответы, цены.",
    price: "по запросу",
    pricing: "paid",
    website: "https://avitolog.ru",
    status: "active",
    lastChecked: "2026-08-18",
    api: "unofficial",
    risk: false,
  },
];
