import { getDb } from "../src/lib/db/index";

export const VIBE_GLOSSARY_TERMS = [
  // ═══════════════════════════════════════════════════════════
  // 1. ОСНОВЫ ВАЙБКОДИНГА И РОЛИ
  // ═══════════════════════════════════════════════════════════
  {
    term: "Вайбкодинг (Vibe coding)",
    slug: "vibe-coding",
    definition: "Стиль разработки, при котором человек выступает в роли арт-директора или продуктового менеджера, а основную массу кода пишет ИИ-агент (Cursor, Claude Code, Composer). Разработчик управляет процессом через высокоуровневые промпты, полагаясь на интуицию и общее ощущение правильности работы интерфейса.",
    simpleExplanation: "Ты арт-директор, а ИИ пишет весь код.",
    example: "Вместо 2 дней написания CSS и форм на React вы надиктовываете промпт за 5 минут и проверяете готовый экран в браузере.",
    vibeUsage: "«Вайбкожу новый SaaS под чашку кофе — Cursor сам поднял всю авторизацию»",
    devSay: "Разработка на естественном языке с делегированием реализации LLM-агентам.",
    level: "vibe",
    category: "vibe-process",
    relatedTerms: "vibe-code, prompt-engineering, agentic-coding, vibe-check",
    sortOrder: 1,
  },
  {
    term: "Вайб-код (Vibe code)",
    slug: "vibe-code",
    definition: "Код, сгенерированный ИИ-агентом, который работает и выполняет задачу, но разработчик до конца не вникал в каждую строчку синтаксиса. Держится на удачном сочетании промпта, контекста и встроенных библиотек.",
    simpleExplanation: "Код от ИИ, который работает, даже если ты не читал каждую строчку.",
    example: "Файл на 400 строк с анимацией на Framer Motion и расчетом координат, сгенерированный за 1 клик.",
    vibeUsage: "«Главное не трогать этот кусок руками — это чистый вайб-код, он работает и ладно»",
    devSay: "AI-generated код без детального ручного code review.",
    level: "vibe",
    category: "vibe-process",
    relatedTerms: "vibe-coding, magic-code, fragile-code",
    sortOrder: 2,
  },
  {
    term: "Вайб-кодер (Vibe coder)",
    slug: "vibe-coder",
    definition: "Создатель продуктов нового поколения, который минимально пишет код вручную. Его главные навыки — декомпозиция задач, формулирование ценности (JTBD), промпт-инжиниринг и проверка результата через артефакты.",
    simpleExplanation: "Создатель продуктов, который кодит промптами и оркеструет агентов.",
    example: "Соло-фаундер, запускающий 3 работающих микро-сервиса в месяц в одиночку с помощью Cursor и Claude.",
    vibeUsage: "«Я не чистый бэкендер, я вайб-кодер — за вечер собрал CRM для клиента»",
    devSay: "AI-assisted Product Engineer / Solo Founder.",
    level: "vibe",
    category: "vibe-process",
    relatedTerms: "vibe-coding, agentic-coding, prompt-whispering",
    sortOrder: 3,
  },
  {
    term: "Промпт-инжиниринг (Prompt engineering)",
    slug: "prompt-engineering",
    definition: "Инженерная дисциплина составления структурированных инструкций для ИИ-моделей. Включает задание системной роли, контекста проекта, XML-контрактов, Few-Shot примеров и ограничений на формат вывода.",
    simpleExplanation: "Искусство писать инструкции для ИИ так, чтобы получать точный результат с первого раза.",
    example: "Промпт с XML-тегами <role>, <context>, <constraints> и схемой ответа в JSON.",
    vibeUsage: "«Нормально распиши контекст через теги — без промпт-инжиниринга он нагаллюцинирует»",
    devSay: "Формулирование детерминированных контекстных инструкций для LLM.",
    level: "modern",
    category: "vibe-process",
    relatedTerms: "prompt-whispering, system-prompt, zero-shot-few-shot",
    sortOrder: 4,
  },
  {
    term: "Промпт-шептание (Prompt whispering)",
    slug: "prompt-whispering",
    definition: "Высший пилотаж взаимодействия с ИИ: аккуратное, точное направление агента с помощью коротких, контекстно-обогащенных микро-промптов вместо огромных простыней текста, что исключает галлюцинации и расфокус.",
    simpleExplanation: "Умение управлять агентом короткими и хирургически точными подсказками.",
    example: "Вместо 'перепиши всю авторизацию' — 'в auth/route.ts добавь проверку session.user.role === ADMIN перед возвратом 403'.",
    vibeUsage: "«Не строчи простыню на 5 экранов, примени шептание — укажи точную функцию и файл»",
    devSay: "Surgical context prompting / Micro-prompting.",
    level: "senior",
    category: "vibe-process",
    relatedTerms: "prompt-engineering, blind-prompt, prompt-drift",
    sortOrder: 5,
  },
  {
    term: "Агентная разработка (Agentic coding)",
    slug: "agentic-coding",
    definition: "Парадигма, в которой ИИ-агенты наделены автономностью: они сами читают файловую систему, запускают терминал, проверяют линтеры, читают логи ошибок и циклически исправляют баги до получения зеленого билда.",
    simpleExplanation: "Когда ИИ сам запускает команды, тестирует код и исправляет ошибки.",
    example: "Cursor Composer в Agent Mode сам читает ошибку TypeScript, находит нужный тип и вносит правку без участия человека.",
    vibeUsage: "«Переключился в Agentic mode — агент сам прогнал миграцию и починил роут»",
    devSay: "Autonomous multi-step execution with tool calling & self-correction.",
    level: "modern",
    category: "vibe-arch",
    relatedTerms: "agent-swarm, mcp, looping",
    sortOrder: 6,
  },
  {
    term: "Рой агентов (Agent swarm)",
    slug: "agent-swarm",
    definition: "Архитектура разработки, где специализированные ИИ-агенты распределяют обязанности: агент-автор пишет код, агент-валидатор прогоняет тесты, агент-аудитор проверяет безопасность и доступность.",
    simpleExplanation: "Команда специализированных ИИ-ботов, работающих сообща над одной задачей.",
    example: "Конвейер ProektMap: resheniya-author → resheniya-validator → resheniya-auditor.",
    vibeUsage: "«Запустил рой: один пилит фронт, второй проверяет типы, третий пишет документацию»",
    devSay: "Multi-agent orchestration pipeline.",
    level: "senior",
    category: "vibe-arch",
    relatedTerms: "agentic-coding, mcp, prompt-whispering",
    sortOrder: 7,
  },

  // ═══════════════════════════════════════════════════════════
  // 2. ЖАРГОН КАЧЕСТВА КОДА И ИИ-СЛОПА
  // ═══════════════════════════════════════════════════════════
  {
    term: "ИИ-слоп (AI slop / Нейрослоп)",
    slug: "ai-slop",
    definition: "Низкокачественный, шаблонный, раздутый и бессмысленный код или контент, сгенерированный ИИ без должного контроля человека. Характеризуется избыточными комментариями-очевидностями, устаревшими паттернами и отсутствием архитектурной мысли.",
    simpleExplanation: "Низкосортный мусор от нейросети, который выглядит правдоподобно, но сделан кое-как.",
    example: "Функция на 80 строк с 15 комментариями '// Increment counter', тремя вложенными try-catch и устаревшим синтаксисом 2020 года.",
    vibeUsage: "«Cursor выдал чистый слоп — пришлось откатить и дать нормальный контекст»",
    devSay: "Low-quality hallucinated boilerplate.",
    level: "jargon",
    category: "vibe-slang",
    relatedTerms: "copilot-clutter, deslopification, div-soup",
    sortOrder: 8,
  },
  {
    term: "Копилот-мусор (Copilot clutter)",
    slug: "copilot-clutter",
    definition: "Избыточный, неэффективный код, предложенный автодополнением ИИ, который разработчик бездумно принял нажатием Tab (например, 40 строк ненужных проверок там, где хватило бы одной строчки).",
    simpleExplanation: "Ненужные куски кода, которые ты принял табом, не глядя.",
    example: "Дублирующиеся вспомогательные функции в каждом втором файле вместо одного импорта из utils.",
    vibeUsage: "«Почисти копилот-мусор из репозитория — у нас половина файлов забита заглушками»",
    devSay: "Redundant AI autocomplete boilerplate.",
    level: "jargon",
    category: "vibe-slang",
    relatedTerms: "ai-slop, deslopification, zombie-code",
    sortOrder: 9,
  },
  {
    term: "Раздувание бойлерплейта (Boilerplate bloat)",
    slug: "boilerplate-bloat",
    definition: "Ситуация, когда ИИ генерирует излишне многословный код 'на все случаи жизни' с десятками неиспользуемых интерфейсов, хелперов и обработчиков, которые только усложняют чтение проекта.",
    simpleExplanation: "Когда ИИ написал 500 строк шаблонов для задачи на 10 строк.",
    example: "Создание Redux-хранилища с 6 файлами actions/reducers для переключения одной темной темы.",
    vibeUsage: "«Снова раздувание бойлерплейта — попроси агента использовать нативный Zustand или Server Actions»",
    devSay: "Over-engineered boilerplate generated by LLM.",
    level: "senior",
    category: "vibe-slang",
    relatedTerms: "ai-slop, inline-style-soup",
    sortOrder: 10,
  },
  {
    term: "Хрупкий код (Fragile code)",
    slug: "fragile-code",
    definition: "Код от ИИ, который идеально работает на основном счастливом сценарии (Happy Path), но падает с ошибкой при любом нестандартном вводе, пустом массиве или медленном интернете, так как ИИ не учел краевые случаи.",
    simpleExplanation: "Код, который работает только в идеальных условиях и ломается от любого чиха.",
    example: "Парсер, падающий с TypeError: undefined is not an object, если API вернуло пустой список пользователей.",
    vibeUsage: "«Этот компонент хрупкий — проверь его на пустой список и ошибку 500»",
    devSay: "Unresilient code lacking edge-case handling.",
    level: "vibe",
    category: "vibe-process",
    relatedTerms: "vibe-check, hallucination, looping",
    sortOrder: 11,
  },
  {
    term: "Синтетический мусор (Synthetic garbage)",
    slug: "synthetic-garbage",
    definition: "Сгенерированный ИИ код, который настолько нелогичен, содержит ошибки компиляции и выдуманные функции, что его проще удалить целиком и переписать промпт с нуля, чем тратить время на исправление.",
    simpleExplanation: "Код настолько сломан, что его проще стереть, чем чинить.",
    example: "Файл с 20 синтаксическими ошибками, где агент перемешал Python-синтаксис с TypeScript.",
    vibeUsage: "«Не пытайся это дебажить, это синтетический мусор — жми Cmd+Z и начни с чистого промпта»",
    devSay: "Unrecoverable corrupted AI generation.",
    level: "jargon",
    category: "vibe-slang",
    relatedTerms: "ai-slop, deslopification",
    sortOrder: 12,
  },
  {
    term: "Долг промпт-инжиниринга (Prompt engineering debt)",
    slug: "prompt-engineering-debt",
    definition: "Вид технического долга, при котором кодовая база завязана на нестабильные или не зафиксированные системные промпты, и после очередного обновления модели провайдером вся автоматизация внезапно ломается.",
    simpleExplanation: "Техдолг из-за промптов, которые ломаются после апдейта нейросети.",
    example: "Бот работал на Claude 3.5 Sonnet, а после переключения на новую версию перестал отдавать правильный JSON.",
    vibeUsage: "«У нас вылез долг промпт-инжиниринга: старый промпт парсера не совместим с новой моделью»",
    devSay: "LLM dependency & prompt regression debt.",
    level: "senior",
    category: "vibe-arch",
    relatedTerms: "prompt-engineering, system-prompt",
    sortOrder: 13,
  },
  {
    term: "Деслопификация (Deslopification)",
    slug: "deslopification",
    definition: "Процесс генеральной уборки проекта: удаление шаблонного ИИ-мусора, очевидных комментариев, хардкода стилей и приведение архитектуры к чистым инженерным стандартам.",
    simpleExplanation: "Чистка кодовой базы от следов неаккуратной работы нейросети.",
    example: "Удаление 30 лишних комментариев '// Function to calculate', вынос цветов в токены и упрощение структуры компонентов.",
    vibeUsage: "«Перед релизом на прод проведи деслопификацию — вычисти лишние логи и захардкоженные стили»",
    devSay: "AI code cleanup & refactoring to human standards.",
    level: "vibe",
    category: "vibe-slang",
    relatedTerms: "ai-slop, copilot-clutter, div-soup",
    sortOrder: 14,
  },

  // ═══════════════════════════════════════════════════════════
  // 3. ВЗАИМОДЕЙСТВИЕ С ИИ-АГЕНТОМ (ПРОЦЕСС И БАГИ)
  // ═══════════════════════════════════════════════════════════
  {
    term: "Галлюцинация (Hallucination) / Фантомная библиотека",
    slug: "hallucination",
    definition: "Ситуация, когда языковая модель уверенно придумывает несуществующие функции, методы или npm-пакеты, которых никогда не было в природе, основываясь на вероятностном распределении слов.",
    simpleExplanation: "Когда ИИ уверенно врет и выдумывает несуществующие функции или библиотеки.",
    example: "import { autoFormatPhone } from 'lucide-react' — модель выдумала утилиту для иконочной библиотеки.",
    vibeUsage: "«Cursor установил пакет-призрак и искренне удивляется, почему npm run build падает»",
    devSay: "LLM hallucination / Non-existent API invention.",
    level: "modern",
    category: "vibe-process",
    relatedTerms: "component-hallucination, tailwind-hallucination, looping",
    sortOrder: 15,
  },
  {
    term: "Промпт-дрейф (Prompt drift)",
    slug: "prompt-drift",
    definition: "Явление, при котором ИИ-агент в ходе длинной сессии чата постепенно забывает исходную цель или правила проекта, уходя в сторону и начиная переписывать не те файлы.",
    simpleExplanation: "Когда к 10-му сообщению ИИ забыл, что вы вообще делали в начале.",
    example: "Вы просили поправить цвет кнопки, а через 5 итераций агент начал переписывать всю схему базы данных.",
    vibeUsage: "«У агента пошел промпт-дрейф — открывай новый чистый чат и давай контекст заново»",
    devSay: "Context degradation across long conversation threads.",
    level: "vibe",
    category: "vibe-process",
    relatedTerms: "token-burning, context-window, prompt-whispering",
    sortOrder: 16,
  },
  {
    term: "Петля (Looping) / Бесконечный цикл",
    slug: "looping",
    definition: "Классическая ловушка вайбкодинга: ИИ исправляет баг А, создавая ошибку Б, затем чинит Б, возвращая баг А, и так по бесконечному кругу, сжигая токены.",
    simpleExplanation: "Когда ИИ чинит одну ошибку, ломает другую, а потом возвращает первую.",
    example: "Агент 5 раз подряд меняет 'use client' на серверный компонент и обратно, не понимая корень проблемы.",
    vibeUsage: "«Агент вошел в петлю — останови генерацию, прочитай лог терминала сам и укажи точную строку»",
    devSay: "Agentic fix-break-fix circular loop.",
    level: "vibe",
    category: "vibe-process",
    relatedTerms: "agentic-coding, zombie-code, token-burning",
    sortOrder: 17,
  },
  {
    term: "Зомби-код (Zombie code)",
    slug: "zombie-code",
    definition: "Фрагменты старого кода или удаленные импорты, которые ИИ упорно продолжает восстанавливать и предлагать исправить, потому что они остались в истории чата или кэше контекста.",
    simpleExplanation: "Удаленный код, который ИИ упорно пытается вернуть обратно.",
    example: "Вы удалили старую библиотеку moment.js, а агент в каждом ответе снова вставляет import moment from 'moment'.",
    vibeUsage: "«Опять зомби-код вылез — почисти историю чата в Cursor, он цепляется за старые файлы»",
    devSay: "Stale context resurrection.",
    level: "jargon",
    category: "vibe-slang",
    relatedTerms: "prompt-drift, looping, copilot-clutter",
    sortOrder: 18,
  },
  {
    term: "Магический код (Magic code)",
    slug: "magic-code",
    definition: "Решение от ИИ, которое выглядит неочевидным, переусложненным или странным, но при этом безупречно работает и проходит тесты. Создатель боится прикасаться к нему руками.",
    simpleExplanation: "Странный код от ИИ, который почему-то работает, и его страшно трогать.",
    example: "Сложное регулярное выражение на 120 символов для парсинга адресов, написанное нейросетью за 2 секунды.",
    vibeUsage: "«Не лезь в этот модуль — там магический код, тронешь и всё посыплется»",
    devSay: "Opaque working AI-generated solution.",
    level: "vibe",
    category: "vibe-slang",
    relatedTerms: "vibe-code, fragile-code, code-jungle",
    sortOrder: 19,
  },
  {
    term: "Вайб-рефакторинг (Vibe refactoring)",
    slug: "vibe-refactoring",
    definition: "Запрос к ИИ в духе 'сделай красивее', 'причеши код' или 'улучши архитектуру' без конкретных технических требований, что обычно приводит к непредсказуемой поломке рабочей логики.",
    simpleExplanation: "Просьба к ИИ 'сделать красиво' без четкого ТЗ, которая ломает всё подряд.",
    example: "Промпт: 'Сделай этот компонент современнее' → ИИ удалил 3 нужных пропса и сломал авторизацию.",
    vibeUsage: "«Никакого вайб-рефакторинга перед деплоем! Формулируй точные правила: вынеси типы в types.ts»",
    devSay: "Unconstrained subjective refactoring.",
    level: "vibe",
    category: "vibe-process",
    relatedTerms: "prompt-whispering, blind-prompt, deslopification",
    sortOrder: 20,
  },
  {
    term: "Вайб-чек (Vibe check)",
    slug: "vibe-check",
    definition: "Быстрая экспресс-проверка работоспособности фичи глазами в браузере: кликнуть по кнопке, проверить анимацию и адаптивность на 375px без запуска тяжелых unit-тестов.",
    simpleExplanation: "Быстрая ручная проверка глазами: открыл страницу, потыкал кнопки, работает.",
    example: "После правок агента открыть мобильный вид в DevTools и убедиться, что меню не съехало.",
    vibeUsage: "«Я сделал вайб-чек на мобилке — верстка ровная, можно пушить»",
    devSay: "Visual smoke testing / Manual UI verification.",
    level: "vibe",
    category: "vibe-process",
    relatedTerms: "vibe-coding, pixel-perfect-prompt",
    sortOrder: 21,
  },
  {
    term: "Слепой промпт (Blind prompt)",
    slug: "blind-prompt",
    definition: "Грубая ошибка: просьба к ИИ 'исправь ошибку' или 'добавь кнопку' без прикрепления файла, фрагмента кода, точного лога терминала или структуры данных.",
    simpleExplanation: "Запрос к ИИ без контекста: 'почини ошибку', когда ИИ даже не видит код.",
    example: "Промпт: 'У меня кнопка не нажимается, почему?' без указания компонента и консольных логов.",
    vibeUsage: "«Хватит слать слепые промпты — прикрепи @page.tsx и ошибку из консоли через Alt+L»",
    devSay: "Context-deprived prompt leading to guaranteed hallucination.",
    level: "vibe",
    category: "vibe-process",
    relatedTerms: "prompt-engineering, hallucination, prompt-whispering",
    sortOrder: 22,
  },
  {
    term: "Копилот-зависимость (Copilot dependency)",
    slug: "copilot-dependency",
    definition: "Психологическое состояние создателя, при котором он теряет способность писать базовый синтаксис или формулировать алгоритмы в чистом блокноте без постоянных подсказок ИИ.",
    simpleExplanation: "Когда без подсказок нейросети уже не помнишь, как объявить цикл или функцию.",
    example: "Разработчик зависает на 5 минут перед чистым экраном, пытаясь вспомнить синтаксис fetch запроса.",
    vibeUsage: "«У меня развилась копилот-зависимость — без табуляции в Cursor уже даже console.log лень писать»",
    devSay: "Cognitive atrophy from AI autocomplete overreliance.",
    level: "jargon",
    category: "vibe-slang",
    relatedTerms: "vibe-coding, ai-slop",
    sortOrder: 23,
  },
  {
    term: "Джангл (Code jungle)",
    slug: "code-jungle",
    definition: "Запутанные дебри кода, возникшие после десятка итераций правок разными агентами, где никто уже не понимает общую архитектуру, но всё держится на честном слове.",
    simpleExplanation: "Непроходимые дебри спагетти-кода, накопленные за 20 правок от нейросети.",
    example: "Файл на 1500 строк с переплетенными стейтами, локальными стилями и дублирующимися хуками.",
    vibeUsage: "«Тут уже настоящий джангл — надо декомпозировать на 4 маленьких компонента»",
    devSay: "Severe architectural entropy in AI-generated codebase.",
    level: "jargon",
    category: "vibe-slang",
    relatedTerms: "css-spaghetti, div-soup, deslopification",
    sortOrder: 24,
  },

  // ═══════════════════════════════════════════════════════════
  // 4. ДИЗАЙН, UI-СЛОП И ВЕРСТКА
  // ═══════════════════════════════════════════════════════════
  {
    term: "Промпт-ту-UI (Prompt-to-UI)",
    slug: "prompt-to-ui",
    definition: "Процесс генерации готового интерактивного интерфейса (React, Tailwind, CSS) исключительно из текстового описания задачи в специализированных средах (v0, Bolt, Lovable).",
    simpleExplanation: "Генерация готового экрана приложения из текстового описания.",
    example: "Описали 'дашборд криптокошелька с графиком цен' → получили готовый JSX-компонент.",
    vibeUsage: "«Сначала накидал прототип в Prompt-to-UI, потом закинул код в Cursor и привязал БД»",
    devSay: "Text-to-JSX UI generation.",
    level: "modern",
    category: "vibe-design",
    relatedTerms: "screenshot-to-code, vibe-design, ui-slop",
    sortOrder: 25,
  },
  {
    term: "Скриншот-ту-код (Screenshot-to-Code)",
    slug: "screenshot-to-code",
    definition: "Вайбкодинг-паттерн, при котором разработчик загружает изображение референса или макета в мультимодальную модель (Claude Sonnet 3.7 / GPT-5), а агент воссоздает разметку и стили.",
    simpleExplanation: "Показал нейросети скриншот сайта — получил готовый код верстки.",
    example: "Скриншот карточки товара из Dribbble превращается в готовый компонент на Tailwind за 30 секунд.",
    vibeUsage: "«Сделай скриншот-ту-код этого блока и примени наши цвета из globals.css»",
    devSay: "Vision-based code extraction from UI raster mocks.",
    level: "vibe",
    category: "vibe-design",
    relatedTerms: "prompt-to-ui, figma-to-code-illusion, vibe-design",
    sortOrder: 26,
  },
  {
    term: "Иллюзия Фигма-ту-код (Figma-to-Code illusion)",
    slug: "figma-to-code-illusion",
    definition: "Заблуждение новичков о том, что ИИ может в один клик превратить сложный многослойный макет из Figma в чистый production-ready код без необходимости ручной доработки адаптивности и семантики.",
    simpleExplanation: "Иллюзия, что нейросеть идеально скопирует сложный макет из Figma в прод без косяков.",
    example: "Плагин выдал 3000 строк абсолютного позиционирования (top: 142px, left: 38px), непригодного для мобилок.",
    vibeUsage: "«Не поддавайся иллюзии Фигма-ту-код — собирай на готовых токенах и flex-сетке»",
    devSay: "Naive expectation of perfect automated Figma translation.",
    level: "senior",
    category: "vibe-design",
    relatedTerms: "design-token-drift, inline-style-soup",
    sortOrder: 27,
  },
  {
    term: "Вайб-дизайн (Vibe design)",
    slug: "vibe-design",
    definition: "Подход к стилизации, при котором создатель не высчитывает каждый пиксель в редакторе, а задает общее настроение и ориентиры: 'в стиле Stripe, чистый минимализм, мягкие тени и высокая контрастность'.",
    simpleExplanation: "Проектирование дизайна через настроение и ассоциации, а не по пикселям.",
    example: "Промпт: 'Сделай карточку премиальной: темный фон #111, тонкая рамка rgba(255,255,255,0.1), акцентная изумрудная кнопка'.",
    vibeUsage: "«Вайб-дизайн сработал на ура — лендинг выглядит как у западного стартапа»",
    devSay: "Descriptor-driven UI styling.",
    level: "vibe",
    category: "vibe-design",
    relatedTerms: "prompt-to-ui, pixel-perfect-prompt",
    sortOrder: 28,
  },
  {
    term: "Дрейф дизайн-токенов (Design token drift)",
    slug: "design-token-drift",
    definition: "Антипаттерн, при котором ИИ игнорирует зафиксированные в проекте CSS-переменные (var(--color-accent)) и начинает вставлять случайные hex-цвета (#3b82f6) и магические числа, ломая цветовую схему.",
    simpleExplanation: "Когда ИИ вместо переменных проекта начинает лепить случайные цвета и отступы невпопад.",
    example: "Вместо var(--color-bg-primary) агент написал background: #f3f7fa, и в темной теме появился белый кусок.",
    vibeUsage: "«Опять дрейф токенов: напомни агенту в правилах, что у нас есть tokens.css»",
    devSay: "Violation of unified design system tokens in generated code.",
    level: "senior",
    category: "vibe-design",
    relatedTerms: "tailwind-hallucination, inline-style-soup, frankenstein-ui",
    sortOrder: 29,
  },
  {
    term: "Галлюцинация Tailwind (Tailwind hallucination)",
    slug: "tailwind-hallucination",
    definition: "Ситуация, когда ИИ придумывает несуществующие классы Tailwind CSS (например, text-super-bold, bg-custom-glow-500, flex-center-all), которые не поддерживаются без кастомного конфига.",
    simpleExplanation: "Когда ИИ выдумывает несуществующие классы Tailwind CSS.",
    example: "class='flex-super-center shadow-ultra-lg' — стили не применились, верстка развалилась.",
    vibeUsage: "«Агент нагаллюцинировал классы Tailwind — проверь официальную документацию»",
    devSay: "Fictitious utility class generation.",
    level: "modern",
    category: "vibe-design",
    relatedTerms: "hallucination, design-token-drift",
    sortOrder: 30,
  },
  {
    term: "Война Z-индексов (Z-Index wars)",
    slug: "z-index-wars",
    definition: "Хаотичное накручивание значений z-index агентом (z-[999], z-[9999], z-[999999]) для решения проблем с перекрытием слоев вместо правильного управления stacking context.",
    simpleExplanation: "Когда ИИ лепит z-index: 99999 везде, где элементы перекрывают друг друга.",
    example: "Выпадающее меню с z-[9999] перекрывается модальным окном с z-[9999999], а кнопка закрытия перестает нажиматься.",
    vibeUsage: "«У нас в шапке началась война z-индексов — модалка не кликается»",
    devSay: "Uncontrolled stacking context inflation.",
    level: "jargon",
    category: "vibe-design",
    relatedTerms: "css-spaghetti, div-soup",
    sortOrder: 31,
  },
  {
    term: "Суп из инлайн-стилей (Inline style soup)",
    slug: "inline-style-soup",
    definition: "Антипаттерн генерации, когда ИИ, не разобравшись с классами, начинает массово навешивать тяжелые объекты style={{ margin: '14px', display: 'flex' }} прямо в JSX, делая код нечитаемым.",
    simpleExplanation: "Когда весь код загажен атрибутами style={{...}} вместо аккуратных классов.",
    example: "Каждый второй div содержит 15 строчек инлайн-стилей с жестко зашитыми размерами в пикселях.",
    vibeUsage: "«Вычисти этот суп из инлайн-стилей — вынеси оформление в CSS-модуль или токены»",
    devSay: "Excessive inline JSX styling anti-pattern.",
    level: "jargon",
    category: "vibe-design",
    relatedTerms: "div-soup, design-token-drift, deslopification",
    sortOrder: 32,
  },
  {
    term: "Компонентная галлюцинация (Component hallucination)",
    slug: "component-hallucination",
    definition: "Ситуация, когда ИИ импортирует или использует компонент, которого нет в вашем проекте (например, <MagicDatePicker /> или <BadgeGlow />), потому что помнит его из других библиотек.",
    simpleExplanation: "Когда ИИ вставляет в код выдуманный компонент, которого нет в проекте.",
    example: "import { SuperModal } from '@/components/ui/super-modal' — файл не существует, билд падает.",
    vibeUsage: "«Опять компонентная галлюцинация — агент забыл, какие компоненты есть в проекте»",
    devSay: "Importing phantom non-existent components.",
    level: "modern",
    category: "vibe-design",
    relatedTerms: "hallucination, tailwind-hallucination",
    sortOrder: 33,
  },
  {
    term: "UI-слоп (UI slop)",
    slug: "ui-slop",
    definition: "Визуально бездушный, пластиковый интерфейс с шаблонными неоновыми фиолетово-синими градиентами, кривыми тенями и гигантскими кнопками, по которому сразу видно, что дизайнер к нему не прикасался.",
    simpleExplanation: "Типичный пластмассовый дизайн от нейросети с фиолетовыми градиентами и кривыми отступами.",
    example: "Типовой лендинг с темным фоном, светящимися фиолетовыми шарами и шаблонными иконками-роботами.",
    vibeUsage: "«Переделай этот UI-слоп — сделай строгую монохромную сетку в стиле ProektMap»",
    devSay: "Generic unrefined AI-generated user interface.",
    level: "jargon",
    category: "vibe-design",
    relatedTerms: "ai-slop, frankenstein-ui, div-soup",
    sortOrder: 34,
  },
  {
    term: "Див-суп (Div soup)",
    slug: "div-soup",
    definition: "Бессмысленная многослойная вложенность из десятков тегов <div><div><div>, сгенерированная ИИ ради центрирования одной иконки, полностью игнорирующая семантический HTML.",
    simpleExplanation: "Десять тегов <div> внутри друг друга ради одной несчастной иконки.",
    example: "7 вложенных div-контейнеров вокруг одного параграфа текста.",
    vibeUsage: "«Упрости этот див-суп — замени на один семантический <header> с flexbox»",
    devSay: "Excessive non-semantic DOM nesting.",
    level: "jargon",
    category: "vibe-design",
    relatedTerms: "inline-style-soup, css-spaghetti",
    sortOrder: 35,
  },
  {
    term: "Франкенштейн-интерфейс (Frankenstein UI)",
    slug: "frankenstein-ui",
    definition: "Интерфейс, сшитый ИИ из кусков совершенно разных дизайн-систем: одна кнопка со скруглением 99px из Material, вторая квадратная со строгой рамкой, а таблица со шрифтом из 2010 года.",
    simpleExplanation: "Экран, где половина кнопок круглые, половина квадратные, и всё из разных стилей.",
    example: "Смесь стилей Bootstrap, Tailwind и Windows 95 в одном модальном окне.",
    vibeUsage: "«У нас получился Франкенштейн-интерфейс — зафиксируй единую дизайн-систему в промпте»",
    devSay: "Incoherent UI stitched from disparate design systems.",
    level: "jargon",
    category: "vibe-design",
    relatedTerms: "ui-slop, design-token-drift",
    sortOrder: 36,
  },
  {
    term: "Амнезия доступности (A11y amnesia)",
    slug: "a11y-amnesia",
    definition: "Склонность ИИ генерировать внешне красивый интерфейс, который абсолютно недоступен для клавиатуры, не имеет aria-лейблов, alt-тегов у картинок и правильного цветового контраста.",
    simpleExplanation: "Красивый дизайн от ИИ, который невозможно открыть с клавиатуры и в котором нет aria-тегов.",
    example: "Кликабельный элемент сделан через <div onClick=...> без tabIndex, role='button' и поддержки Enter.",
    vibeUsage: "«У агента амнезия доступности — добавь правило про aria-label и фокусы кнопок»",
    devSay: "Complete omission of accessibility (A11y) standards by LLM.",
    level: "senior",
    category: "vibe-design",
    relatedTerms: "div-soup, ui-slop",
    sortOrder: 37,
  },
  {
    term: "Остаточный плейсхолдер (Lingering placeholder)",
    slug: "lingering-placeholder",
    definition: "Забытый текст-рыба (Lorem ipsum, 'John Doe', 'Card description goes here'), который ИИ сгенерировал во время верстки, а создатель забыл заменить на живой текст перед публикацией.",
    simpleExplanation: "Забытая 'рыба' (Lorem Ipsum), которую оставили на живом сайте.",
    example: "На проде в карточке тарифа висит надпись 'Feature description placeholder text'.",
    vibeUsage: "«Проверь лендинг на остаточные плейсхолдеры перед запуском рекламы»",
    devSay: "Unreplaced dummy mock content in production build.",
    level: "vibe",
    category: "vibe-design",
    relatedTerms: "vibe-check, ai-slop",
    sortOrder: 38,
  },
  {
    term: "Пиксель-перфект промпт (Pixel-perfect prompt)",
    slug: "pixel-perfect-prompt",
    definition: "Идеально выверенное техническое задание для ИИ, в котором указаны точные размеры контейнера, брейкпоинты, шрифтовые токены и контрастность, сводящее вероятность слопа к нулю.",
    simpleExplanation: "Промпт с точными отступами, цветами и правилами, дающий безупречный результат.",
    example: "Промпт: 'Max-width 1200px, padding 24px, grid 3 колонки (1 колонка на <768px), gap 16px, background var(--color-surface)'.",
    vibeUsage: "«Написал пиксель-перфект промпт — Cursor собрал идеальный адаптивный каталог с первого раза»",
    devSay: "Strictly constrained UI specification prompt.",
    level: "senior",
    category: "vibe-design",
    relatedTerms: "prompt-engineering, vibe-design",
    sortOrder: 39,
  },
  {
    term: "CSS-спагетти (CSS spaghetti)",
    slug: "css-spaghetti",
    definition: "Файл стилей после 15 итераций правок от ИИ, где старые неиспользуемые правила конфликтуют с новыми, везде проставлены !important, а мелкая правка ломает половину сайта.",
    simpleExplanation: "Каша из стилей с десятками !important, где правка кнопки ломает шапку сайта.",
    example: "Файл на 900 строк с 40 правилами !important и дублирующимися медиа-запросами.",
    vibeUsage: "«Тут уже CSS-спагетти — давай выкинем этот файл и соберем на чистых токенах»",
    devSay: "Unmaintainable CSS technical debt created by iterative AI patches.",
    level: "jargon",
    category: "vibe-design",
    relatedTerms: "z-index-wars, inline-style-soup, div-soup",
    sortOrder: 40,
  },

  // ═══════════════════════════════════════════════════════════
  // 5. АРХИТЕКТУРА И ТЕХНИЧЕСКИЕ ТЕРМИНЫ
  // ═══════════════════════════════════════════════════════════
  {
    term: "Контекстное окно (Context window)",
    slug: "context-window",
    definition: "Максимальный объем информации (в токенах), который языковая модель может удерживать в оперативной памяти за один раз. При его превышении старая часть разговора безвозвратно стирается.",
    simpleExplanation: "Объем оперативной памяти ИИ. Чем оно больше, тем больше файлов проекта модель помнит одновременно.",
    example: "Контекстное окно в 200 000 токенов позволяет загрузить около 500 страниц кода целиком.",
    vibeUsage: "«Не забивай контекстное окно тяжелыми логами — модель начнет тупить»",
    devSay: "Token-bounded memory capacity of an LLM session.",
    level: "modern",
    category: "vibe-arch",
    relatedTerms: "token-burning, prompt-drift, rag",
    sortOrder: 41,
  },
  {
    term: "Сжигание токенов (Token burning)",
    slug: "token-burning",
    definition: "Нерациональный расход лимитов подписки или API-баланса путем отправки гигантских ненужных дампов базы данных, картинок или всей кодовой базы в каждый промпт.",
    simpleExplanation: "Бессмысленная трата денег и лимитов на отправку гигантских лишних файлов нейросети.",
    example: "Прикрепление 50 файлов проекта ради изменения одной строчки в CSS.",
    vibeUsage: "«Это чистое сжигание токенов — используй поиск по символам вместо загрузки всей папки»",
    devSay: "Inefficient token consumption in agent workflows.",
    level: "vibe",
    category: "vibe-arch",
    relatedTerms: "context-window, prompt-whispering",
    sortOrder: 42,
  },
  {
    term: "MCP (Model Context Protocol)",
    slug: "mcp",
    definition: "Открытый стандарт от Anthropic (USB-разъем для AI), позволяющий безопасно подключать языковые модели к базам данных, локальным файлам, серверам и внешним API без написания кастомных интеграций.",
    simpleExplanation: "Стандарт подключения ИИ к базам данных, файлам и инструментам (как USB для компьютера).",
    example: "Подключили PostgreSQL MCP-сервер → Cursor может сам читать схему таблиц и выполнять запросы.",
    vibeUsage: "«Накатил Postgres MCP — агент сам посмотрел реальную схему БД и написал миграцию»",
    devSay: "Open standard for connecting AI agents to external data sources & tools.",
    level: "modern",
    category: "vibe-arch",
    relatedTerms: "agentic-coding, rag, agent-swarm",
    sortOrder: 43,
  },
  {
    term: "Скелет (Skeleton code)",
    slug: "skeleton-code",
    definition: "Базовый каркас файла или модуля (импорты, интерфейсы, пустые функции-заглушки), который создается на первом шаге, чтобы затем пошагово наполнить его логикой без расфокусировки модели.",
    simpleExplanation: "Каркас программы с пустыми функциями и типами, подготовленный для наполнения логикой.",
    example: "Файл с объявлением типов User, Subscription и сигнатур функций createOrder, verifyPayment.",
    vibeUsage: "«Сначала сгенерируй скелет роута с типами, а потом наполним обработчиками»",
    devSay: "Structural scaffolding / Stub module.",
    level: "vibe",
    category: "vibe-arch",
    relatedTerms: "prompt-engineering, data-modeling",
    sortOrder: 44,
  },
  {
    term: "Zero-shot / Few-shot",
    slug: "zero-shot-few-shot",
    definition: "Методы промптинга. Zero-shot — запрос к модели 'в лоб' без примеров. Few-shot — передача в промпте 1–3 эталонных примеров 'вход → идеальный ответ', что повышает точность кода в разы.",
    simpleExplanation: "Zero-shot — без примеров. Few-shot — с показом образцов того, как надо сделать.",
    example: "Показали модели 2 примера правильного Server Action → модель написала третий в точно таком же стиле.",
    vibeUsage: "«Не используй zero-shot для сложного парсера — дай 2 примера (few-shot), и качество вырастет вдвое»",
    devSay: "In-context learning via few-shot exemplar prompting.",
    level: "modern",
    category: "vibe-arch",
    relatedTerms: "prompt-engineering, system-prompt",
    sortOrder: 45,
  },
];

async function seed() {
  const db = await getDb();
  console.log(`Starting upsert of ${VIBE_GLOSSARY_TERMS.length} vibe glossary terms...`);

  let added = 0;
  let updated = 0;

  for (const item of VIBE_GLOSSARY_TERMS) {
    const existing = await db.glossaryTerm.findUnique({
      where: { slug: item.slug },
    });

    if (existing) {
      await db.glossaryTerm.update({
        where: { slug: item.slug },
        data: {
          term: item.term,
          definition: item.definition,
          simpleExplanation: item.simpleExplanation,
          example: item.example,
          vibeUsage: item.vibeUsage,
          devSay: item.devSay,
          level: item.level,
          category: item.category,
          relatedTerms: item.relatedTerms,
          sortOrder: item.sortOrder,
          isPublished: true,
        },
      });
      updated++;
    } else {
      await db.glossaryTerm.create({
        data: {
          term: item.term,
          slug: item.slug,
          definition: item.definition,
          simpleExplanation: item.simpleExplanation,
          example: item.example,
          vibeUsage: item.vibeUsage,
          devSay: item.devSay,
          level: item.level,
          category: item.category,
          relatedTerms: item.relatedTerms,
          sortOrder: item.sortOrder,
          isPublished: true,
        },
      });
      added++;
    }
  }

  console.log(`Finished! Added: ${added}, Updated: ${updated}. Total: ${VIBE_GLOSSARY_TERMS.length}`);
}

seed()
  .then(() => process.exit(0))
  .catch((e) => {
    console.error(e);
    process.exit(1);
  });
