import type { ArsenalStack } from "./types";

export const ARSENAL_STACKS: ArsenalStack[] = [
  {
    slug: "local-ai-pc",
    title: "Локальный AI на ПК",
    mission: "Поднять чат с LLM на своём компьютере за один вечер.",
    audience: "Кто хочет работать без облака / без утечки данных / при слабом VPN",
    focus: "без облака",
    icon: "🖥️",
    definitionOfDone: "Открыт чат с локальной моделью (например Llama 3 / Qwen), ответ приходит без облачного API-ключа.",
    commonMistake: "Сразу качать огромную 35B-модель на ноутбуке с 8 ГБ RAM.",
    status: "published",
    priority: 1,
    tools: ["llm-checker", "ollama", "lm-studio", "open-webui", "llama-cpp", "pinokio", "jan"],
    orderHint: ["LLM Checker — понять железо и модели", "Ollama или LM Studio — поставить рантайм", "Open WebUI — чат + файлы/RAG", "llama.cpp — запасной лёгкий запуск", "Pinokio — соседние AI-приложения", "Jan — альтернативный локальный стол"],
    excelCategories: ["local-ai", "llm"],
    relatedRoutes: [{ href: "/russian-ai-stack", label: "Российский AI-стек" }, { href: "/ai-tools", label: "Каталог AI-инструментов" }, { href: "/resheniya", label: "Готовые решения" }],
  },
  {
    slug: "local-ai-mobile",
    title: "Локальный AI в кармане",
    mission: "Запустить GGUF-модель на телефоне без интернета.",
    audience: "Кто хочет офлайн-ассистента на смартфоне",
    focus: "офлайн",
    icon: "📱",
    definitionOfDone: "Диалог с моделью в авиарежиме (или без Wi‑Fi).",
    commonMistake: "Ждать от телефона качество десктопной 70B.",
    status: "published",
    priority: 2,
    tools: ["pocketpal-ai", "chatterui", "maid", "layla", "mlc-llm"],
    orderHint: ["PocketPal AI — основной офлайн-чат", "ChatterUI — альтернативный UI под GGUF", "Maid — Android + llama.cpp", "Layla — ассистент с памятью на устройстве", "MLC LLM — движок под мобильные"],
    excelCategories: ["local-ai"],
    relatedRoutes: [
      { href: "/russian-ai", label: "Российский AI" },
      { href: "/arsenal/local-ai-pc", label: "Арсенал: локальный AI на ПК" },
      { href: "/resheniya", label: "Готовые решения" },
    ],
  },
  {
    slug: "vibe-coder",
    title: "Агент-кодер / вайбкодинг",
    mission: "От идеи до рабочего кода с проверкой, а не «чат написал и развалилось».",
    audience: "Вайбкодер, junior AI-инженер, кто собирает сайты/приложения с агентом",
    focus: "вайбкодинг",
    icon: "💻",
    definitionOfDone: "Есть репозиторий, агент внёс изменение, есть наблюдаемый проверочный шаг (тест/запуск/превью).",
    commonMistake: "Просить «сделай весь SaaS» одним сообщением без Definition of Done.",
    status: "published",
    priority: 3,
    tools: ["opencode", "superpowers", "ecc", "agent-skills", "understand-anything", "codegraph", "claudexor", "easy-vibe"],
    orderHint: ["OpenCode — открытый кодинг-агент", "Superpowers — план → код → тест", "ECC — планирование и ревью", "Agent Skills — навыки для агента", "Understand Anything / CodeGraph — разобрать проект", "Claudexor — экосистема Claude/Cursor", "Easy-Vibe — учебный трек vibe coding"],
    excelCategories: ["coding", "agents", "learning"],
    relatedRoutes: [
      { href: "/resheniya/saas-product", label: "SaaS-продукт" },
      { href: "/vaibik", label: "Вайбик" },
      { href: "/ui-patterns", label: "UI-Атлас" },
    ],
  },
  {
    slug: "mcp-agents",
    title: "Агенты, скиллы и рабочий контур",
    mission: "Собрать полезного агента, а не коллекцию закладок.",
    audience: "Кто собирает агента с навыками, памятью и доступом к файлам/браузеру",
    focus: "MCP/skills",
    icon: "🧩",
    definitionOfDone: "Агент выполняет одну сквозную задачу (файл + поиск + итоговый отчёт) без ручного копипаста на каждом шаге.",
    commonMistake: "Ставить 50 скиллов до первой успешной задачи.",
    status: "published",
    priority: 4,
    tools: ["whichllm", "hermes-agent", "awesome-hermes-skills", "hermes-skills-hub", "open-interpreter", "stagehand", "kimi-webbridge", "headroom", "mempalace", "agent-reach"],
    orderHint: ["whichllm — выбрать модель", "Hermes Agent — базовый агент", "Awesome Hermes Skills / Hub — набрать навыки", "Open Interpreter — файлы и команды", "Stagehand или Kimi WebBridge — браузер", "Headroom / MemPalace — контекст и память", "Agent Reach — открытый веб этично"],
    excelCategories: ["agents", "coding", "research"],
    relatedRoutes: [
      { href: "/skills", label: "Skills" },
      { href: "/resheniya/telegram-bot", label: "Telegram-бот" },
      { href: "/mcp", label: "MCP-серверы" },
    ],
  },
  {
    slug: "voice-pipeline",
    title: "Голосовой конвейер",
    mission: "Текст ↔ речь ↔ текст в предсказуемом пайплайне.",
    audience: "Кто делает озвучку гидов, подкастов, дубляж, транскрибацию",
    focus: "STT/TTS",
    icon: "🎙️",
    definitionOfDone: "Есть MP3/WAV озвучки + текстовая расшифровка исходника; можно вставить в страницу/видео.",
    commonMistake: "Клонировать чужой голос без прав — в ProektMap только свой/лицензированный материал.",
    status: "published",
    priority: 5,
    tools: ["faster-whisper", "whisper-base", "piper", "kokoro-tts", "supertonic", "qwen3-tts", "voicebox", "voicestudio", "gpt-sovits-russian", "auphonic", "elevenlabs"],
    orderHint: ["Faster-Whisper — речь → текст", "Piper / Kokoro / Supertonic — локальный TTS", "Qwen3-TTS — русский и дизайн голоса", "Voicebox / VoiceStudio — локальная студия", "GPT-SoVITS-Russian — русскоязычный клон", "Auphonic — выровнять громкость", "ElevenLabs — облачный запасной вариант"],
    excelCategories: ["voice"],
    relatedRoutes: [
      { href: "/services/voice-guide-builder", label: "Конструктор голосового гида" },
      { href: "/resheniya", label: "Готовые решения" },
      { href: "/arsenal/short-video", label: "Арсенал: короткие видео" },
    ],
  },
  {
    slug: "listing-photo",
    title: "Картинки для объявлений",
    mission: "Получить чистые, аккуратные фото под витрину без «кричащего AI-арта».",
    audience: "Продавец, карточки товаров, витрины",
    focus: "витрина",
    icon: "🖼",
    definitionOfDone: "Набор из 3–5 фото без мусора на фоне, читаемых на мобиле, готовых к загрузке.",
    commonMistake: "Генерировать «идеальный товар, которого нет» — риск жалоб и банов площадок.",
    status: "published",
    priority: 6,
    tools: ["removerized", "cutitout", "fooocus", "flux-1-schnell", "real-esrgan", "qualityscaler", "finegrain-image-enhancer", "swinir", "ideogram", "canva-magic-layers"],
    orderHint: ["Removerized / CutItOut — убрать фон", "Fooocus / FLUX.1 — варианты по описанию", "Real-ESRGAN / QualityScaler — апскейл", "Finegrain / SwinIR — дожать качество", "Ideogram — текст на картинке", "Canva Magic Layers — слои макета"],
    excelCategories: ["images"],
    relatedRoutes: [{ href: "/avito", label: "Лаборатория Авито" }, { href: "/services/avito-photo-uniquizer", label: "Avito Photo Lab" }, { href: "/resheniya/avito-business", label: "AI-магазин на Авито" }],
  },
  {
    slug: "ethical-research",
    title: "Этичный ресёрч и мониторинг",
    mission: "Собрать факты и сводку без серого OSINT и взлома.",
    audience: "AI-инженер, продукт, конкурентный обзор по открытым источникам",
    focus: "открытые источники",
    icon: "🔍",
    definitionOfDone: "Документ-сводка со ссылками на источники + список «чего не хватает».",
    commonMistake: "Парсить закрытые ЛК и персональные данные — вне рамок ProektMap.",
    status: "published",
    priority: 7,
    tools: ["last30days", "hyperresearch", "open-notebook", "markitdown", "yutori-scouts", "liberty-ai", "autonomous-researcher"],
    orderHint: ["last30days — свежие материалы", "HyperResearch — глубокий поиск", "Open Notebook — PDF/ссылки → вопросы", "MarkItDown — документы в Markdown", "Yutori Scouts — мониторинг темы", "Liberty AI — приватный контур", "Autonomous Researcher — длинные отчёты"],
    excelCategories: ["research", "coding"],
    relatedRoutes: [{ href: "/blog", label: "Блог" }, { href: "/resheniya", label: "Готовые решения" }, { href: "/ai-tools", label: "AI-инструменты" }],
  },
  {
    slug: "rf-stack",
    title: "РФ-дружелюбный рабочий набор",
    mission: "Собрать повседневный контур: модель + код + шлюз.",
    audience: "Кто работает из России и хочет меньше зависимости от VPN",
    focus: "доступность",
    icon: "🇷🇺",
    definitionOfDone: "Пользователь закрывает типичную задачу (текст или код) без «сайт недоступен» как единственного пути.",
    commonMistake: "Считать любой «открытый вес» автоматически легальным для коммерции — проверять лицензии.",
    status: "published",
    priority: 8,
    tools: ["gigachat-3-5", "gigacode", "omniroute", "freellmapi", "openrouter", "better-deepseek"],
    orderHint: ["GigaChat 3.5 — открытая LLM от Sber", "GigaCode — ассистент для кода", "OmniRoute — шлюз к провайдерам", "FreeLLMAPI — роутер бесплатных тарифов", "OpenRouter — запасной мультипровайдер", "Better DeepSeek — усиленный DeepSeek"],
    excelCategories: ["llm", "coding"],
    relatedRoutes: [
      { href: "/russian-ai", label: "Российский AI" },
      { href: "/russian-ai-stack", label: "Российский AI-стек" },
      { href: "/resheniya", label: "Готовые решения" },
    ],
  },
  {
    slug: "seller-content",
    title: "Контент продавца (этично)",
    mission: "Черновик описания + визуал + короткий ролик без серых схем.",
    audience: "Продавцы маркетплейсов / Авито, кому нужны тексты и креатив",
    focus: "тексты+креатив",
    icon: "🛒",
    definitionOfDone: "Готовы: заголовок, описание, 1 обложка, 1 короткий ролик-черновик.",
    commonMistake: "Накрутки, фейковые отзывы, скрытая реклама без маркировки — не поддерживаем.",
    status: "published",
    priority: 9,
    tools: ["ai-marketing-skills", "prompts-chat", "awesome-nano-banana-pro-prompts", "ideogram", "recraft", "openshorts", "elevenlabs-ads-engine", "knowledge-work-plugins"],
    orderHint: ["AI Marketing Skills — приёмы контента", "prompts.chat / Nano Banana — заготовки", "Ideogram / Recraft — обложки с текстом", "OpenShorts — короткий ролик", "ElevenLabs Ads — локализация роликов", "Knowledge Work Plugins — маркетинг-плагины"],
    excelCategories: ["marketing", "prompts", "images", "video"],
    relatedRoutes: [
      { href: "/avito", label: "Лаборатория Авито" },
      { href: "/resheniya/avito-business", label: "AI-магазин на Авито" },
      { href: "/arsenal/listing-photo", label: "Арсенал: картинки для объявлений" },
    ],
  },
  {
    slug: "short-video",
    title: "Короткие видео",
    mission: "Собрать Shorts/Reels из текста или длинного ролика.",
    audience: "Контент, обучение, витрина продукта",
    focus: "Shorts",
    icon: "🎬",
    definitionOfDone: "1 ролик 15–45 сек, есть субтитры или текст озвучки.",
    commonMistake: "Генерировать бесконечные варианты без сценария и CTA.",
    status: "published",
    priority: 10,
    tools: ["openshorts", "awesome-video-prompts", "kling-ai", "aleph-2-0", "video-use", "hyperframes", "synthesia"],
    orderHint: ["OpenShorts — длинное → короткие", "Awesome Video Prompts — промпты", "Kling AI — генерация видео", "Aleph 2.0 — правка существующего", "video-use — автомонтаж с агентом", "HyperFrames — кадры/анимация", "Synthesia — аватарные ролики"],
    excelCategories: ["video", "prompts"],
    relatedRoutes: [
      { href: "/vaibik", label: "Вайбик" },
      { href: "/resheniya/avito-business", label: "AI-магазин на Авито" },
      { href: "/arsenal/voice-pipeline", label: "Голосовой конвейер" },
    ],
  },
  {
    slug: "prompt-ops",
    title: "Промпт-операции",
    mission: "Собрать рабочую библиотеку промптов под свои задачи.",
    audience: "Кто уже пишет промпты и хочет систему, а не хаос в заметках",
    focus: "библиотека",
    icon: "✍️",
    definitionOfDone: "Папка/файл с 10+ промптами под свои миссии + 1 промпт с Negative/ограничениями.",
    commonMistake: "Тащить jailbreak-техники в прод — в продукте не рекомендуем.",
    status: "published",
    priority: 11,
    tools: ["prompts-chat", "biblioteka-promptov-claude-code", "superdesign-library", "awesome-video-prompts", "awesome-gpt-image-2", "model-guidance-ot-openai", "imagetoprompt", "pxpipe"],
    orderHint: ["prompts.chat — открытая библиотека", "Библиотека Claude Code — кодинг-сценарии", "Superdesign Library — UI/лендинги", "Awesome Video / GPT Image — медиа", "Model Guidance — нормы запросов", "ImageToPrompt — референс → промпт", "pxpipe — сжать контекст в изображения"],
    excelCategories: ["prompts", "coding", "images"],
    relatedRoutes: [
      { href: "/prompts", label: "Промпты" },
      { href: "/resheniya/saas-product", label: "SaaS-продукт" },
      { href: "/ui-patterns", label: "UI-Атлас" },
    ],
  },
  {
    slug: "desktop-agent",
    title: "Агент на рабочем столе",
    mission: "Безопасный контур «агент + файлы + браузер» с понятными границами.",
    audience: "Кто хочет, чтобы AI делал действия на ПК, а не только писал текст",
    focus: "действия на ПК",
    icon: "🖥️",
    definitionOfDone: "Агент создал файл, выполнил команду и вернул отчёт; пользователь понимает, какие папки разрешены.",
    commonMistake: "Давать агенту полный доступ к системе без песочницы и бэкапа.",
    status: "published",
    priority: 12,
    tools: ["open-interpreter", "goose", "qclaw", "kimi-work", "stagehand", "hapi", "memanto", "tencentdb-agent-memory", "openhuman"],
    orderHint: ["Open Interpreter — файлы и команды", "Goose — код, команды, тесты", "QClaw / Kimi Work — задачи на машине", "Stagehand — браузерные действия", "HAPI — контроль с телефона", "Memanto / Agent Memory — память", "OpenHuman — мультиагентность"],
    excelCategories: ["agents", "coding"],
    relatedRoutes: [
      { href: "/skills", label: "Skills" },
      { href: "/resheniya/saas-product", label: "SaaS-продукт" },
      { href: "/arsenal/mcp-agents", label: "Арсенал: агенты и скиллы" },
    ],
  },
];

const bySlug = new Map(ARSENAL_STACKS.map((s) => [s.slug, s]));
export function getArsenalStack(slug: string) { return bySlug.get(slug); }
export function getPublishedStacks() {
  return ARSENAL_STACKS.filter((s) => s.status === "published").sort((a, b) => a.priority - b.priority);
}
